using System;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
           // Console.WriteLine("             ___                       \r\n            /   \\\\                     \r\n       /\\\\ | . . \\\\                    \r\n     ////\\\\|     ||                    \r\n   ////   \\\\ ___//\\                    \r\n  ///      \\\\      \\                   \r\n ///       |\\\\      |                  \r\n//         | \\\\  \\   \\                 \r\n/          |  \\\\  \\   \\                \r\n           |   \\\\ /   /                \r\n           |    \\/   /                 \r\n           |     \\\\/|                  \r\n           |      \\\\|                  \r\n           |       \\\\                  \r\n           |        |                  \r\n           |_________\\ ");

           Console.WriteLine(" .           ..         .           .       .           .           .          \r\n      .         .            .          .       .                              \r\n            .         ..xxxxxxxxxx....               .       .             .   \r\n    .             MWMWMWWMWMWMWMWMWMWMWMWMW                       .            \r\n              IIIIMWMWMWMWMWMWMWMWMWMWMWMWMWMttii:        .           .        \r\n .      IIYVVXMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWxx...         .           .\r\n     IWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMx..                  \r\n   IIWMWMWMWMWMWMWMWMWBY%ZACH%AND%OWENMWMWMWMWMWMWMWMWMWMWMWMWMx..        .    \r\n    \"\"MWMWMWMWMWM\"\"\"\"\"\"\"\".  .:..   .\"\"\"\"\"MWMWMWMWMWMWMWMWMWMWMWMWMWti.         \r\n .     \"\"   . `  .: . :. : .  . :.  .  . . .  \"\"\"\"MWMWMWMWMWMWMWMWMWMWMWMWMti= \r\n        . .   :` . :   .  .'.' '....xxxxx...,'. '   ' .\"\"\"YWMWMWMWMWMWMWMWMWMW+\r\n     ; . ` .  . : . .' :  . ..XXXXXXXXXXXXXXXXXXXXx.    `     . \"YWMWMWMWMWMWMW\r\n.    .  .  .    . .   .  ..XXXXXXXXWWWWWWWWWWWWWWWWXXXX.  .     .     \"\"\"\"\"\"\"  \r\n        ' :  : . : .  ...XXXXXWWW\"   W88N88@888888WWWWWXX.   .   .       . .   \r\n   . ' .    . :   ...XXXXXXWWW\"    M88N88GGGGGG888^8M \"WMBX.          .   ..  :\r\n         :     ..XXXXXXXXWWW\"     M88888WWRWWWMW8oo88M   WWMX.     .    :    . \r\n           \"XXXXXXXXXXXXWW\"       WN8888WWWWW  W8@@@8M    BMBRX.         .  : :\r\n  .       XXXXXXXX=MMWW\":  .      W8N888WWWWWWWW88888W      XRBRXX.  .       . \r\n     ....  \"\"XXXXXMM::::. .        W8@889WWWWWM8@8N8W      . . :RRXx.    .     \r\n         ``...'''  MMM::.:.  .      W888N89999888@8W      . . ::::\"RXV    .  : \r\n .       ..'''''      MMMm::.  .      WW888N88888WW     .  . mmMMMMMRXx        \r\n      ..' .            \"\"MMmm .  .       WWWWWWW   . :. :,miMM\"\"\"  : \"\"`    .  \r\n   .                .       \"\"MMMMmm . .  .  .   ._,mMMMM\"\"\"  :  ' .  :        \r\n               .                  \"\"MMMMMMMMMMMMM\"\"\" .  : . '   .        .     \r\n          .              .     .    .                   HM                     \r\n. ");
        }
    }
}
